# -*- coding: utf-8 -*-
"""
================================================================================
V4 無濾網回測腳本 (No Buy Filter Backtest)
================================================================================
測試 V4 模型在取消 Signal_Buy_Filter 限制下的交易績效。
每一天都可以考慮買進，而非僅在 Donchian 突破日。

用途：
- 評估 Buy Filter 對績效的貢獻度
- 比較有/無濾網的交易次數與勝率差異

作者：Phil Liang (Generated by Gemini)
日期：2025-12-08
================================================================================
"""

import os
import sys
import pickle
from datetime import datetime

# Windows UTF-8 設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# 中文字型設定
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
V4_MODELS_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v4')
RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v4_no_filter')
CACHE_DIR = os.path.join(PROJECT_PATH, 'data', 'processed')

SPLIT_DATE = '2023-01-01'  # 回測起始日
INITIAL_CAPITAL = 1_000_000


# =============================================================================
# 無濾網回測器
# =============================================================================
class NoFilterBacktester:
    """
    無濾網回測器：每天都考慮買進訊號，不受 Signal_Buy_Filter 限制
    """
    def __init__(self, buy_model, sell_model, initial_capital=1_000_000):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.initial_capital = initial_capital
        self.trades = []
        self.equity_curve = []
        self.buy_signals = []
        self.sell_signals = []
    
    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        """執行無濾網回測"""
        capital = self.initial_capital
        position = None
        
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        print(f"[Backtest] 回測期間: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Backtest] 資料筆數: {len(df)}")
        print(f"[Backtest] 初始資金: ${capital:,.0f}")
        print("[Backtest] 模式: 無濾網 (每天都可買進)")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            
            # 記錄每日淨值
            if position is not None:
                current_value = capital + position['shares'] * price
            else:
                current_value = capital
            self.equity_curve.append({'date': date, 'value': current_value})
            
            # 處理 NaN
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            # =====================================================================
            # 持有中：檢查賣出
            # =====================================================================
            if position is not None:
                hold_days = i - position['buy_idx']
                current_return = price / position['buy_price']
                
                # Sell Agent 觀察 (Features + Current Return)
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32)
                action, _ = self.sell_model.predict(sell_obs.reshape(1, -1), deterministic=True)
                
                # 停損/停利/AI決策/超時
                stop_loss = current_return < 0.92  # -8% 停損
                should_sell = action[0] == 1 or stop_loss or hold_days >= 120
                
                if should_sell:
                    sell_value = position['shares'] * price
                    profit = sell_value - position['shares'] * position['buy_price']
                    capital += sell_value
                    
                    self.trades.append({
                        'buy_date': position['buy_date'],
                        'buy_price': position['buy_price'],
                        'sell_date': date,
                        'sell_price': price,
                        'return': current_return - 1,
                        'profit': profit,
                        'hold_days': hold_days
                    })
                    self.sell_signals.append((date, price))
                    position = None
            
            # =====================================================================
            # 空手：每天都檢查買入 (無濾網)
            # =====================================================================
            elif position is None:
                buy_obs = obs.reshape(1, -1)
                action, _ = self.buy_model.predict(buy_obs, deterministic=True)
                
                if action[0] == 1:  # Buy
                    invest_amount = capital * 0.9
                    shares = int(invest_amount / price)
                    
                    if shares > 0:
                        cost = shares * price
                        capital -= cost
                        
                        position = {
                            'shares': shares,
                            'buy_price': price,
                            'buy_date': date,
                            'buy_idx': i
                        }
                        self.buy_signals.append((date, price))
        
        return self._calculate_metrics(df)
    
    def _calculate_metrics(self, df: pd.DataFrame) -> dict:
        """計算績效指標"""
        if not self.equity_curve:
            return {}
        
        equity_df = pd.DataFrame(self.equity_curve)
        equity_df['date'] = pd.to_datetime(equity_df['date'])
        equity_df.set_index('date', inplace=True)
        
        initial = self.initial_capital
        final = equity_df['value'].iloc[-1]
        total_return = (final - initial) / initial
        
        days = (equity_df.index[-1] - equity_df.index[0]).days
        years = days / 365.0
        annualized_return = (1 + total_return) ** (1 / years) - 1 if years > 0 else 0
        
        daily_returns = equity_df['value'].pct_change().dropna()
        if len(daily_returns) > 0 and daily_returns.std() > 0:
            sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
        else:
            sharpe = 0
        
        rolling_max = equity_df['value'].cummax()
        drawdown = (equity_df['value'] - rolling_max) / rolling_max
        max_drawdown = drawdown.min()
        
        if self.trades:
            wins = sum(1 for t in self.trades if t['return'] > 0)
            win_rate = wins / len(self.trades)
            avg_return = np.mean([t['return'] for t in self.trades])
            avg_hold_days = np.mean([t['hold_days'] for t in self.trades])
        else:
            win_rate = 0
            avg_return = 0
            avg_hold_days = 0
        
        return {
            'initial_capital': initial,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized_return,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'avg_return': avg_return,
            'avg_hold_days': avg_hold_days,
            'equity_df': equity_df
        }


# =============================================================================
# 主程式
# =============================================================================
def main():
    print("=" * 60)
    print("V4 無濾網回測 (No Buy Filter Backtest)")
    print("=" * 60)
    
    # 建立輸出目錄
    os.makedirs(RESULTS_PATH, exist_ok=True)
    
    # =========================================================================
    # 載入模型
    # =========================================================================
    print("\n[Model] 載入 V4 模型...")
    buy_path = os.path.join(V4_MODELS_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(V4_MODELS_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        print(f"[Error] 模型不存在: {buy_path}")
        print("請先執行 train_v4_models.py")
        sys.exit(1)
    
    buy_model = PPO.load(buy_path)
    sell_model = PPO.load(sell_path)
    print("  ✅ 模型載入成功")
    
    # =========================================================================
    # 載入/計算特徵資料
    # =========================================================================
    print("\n[Data] 準備回測資料...")
    import ptrl_hybrid_system as hybrid
    
    hybrid.load_best_lstm_models()
    
    cache_path = os.path.join(CACHE_DIR, "_TWII_features.pkl")
    if os.path.exists(cache_path):
        print(f"  [Cache] 載入快取: {cache_path}")
        with open(cache_path, 'rb') as f:
            twii_full_df = pickle.load(f)
    else:
        print("  [Compute] 下載並計算特徵...")
        twii_raw = yf.download("^TWII", start="2000-01-01", auto_adjust=True, progress=False)
        if isinstance(twii_raw.columns, pd.MultiIndex):
            twii_raw.columns = twii_raw.columns.get_level_values(0)
        twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=True)
    
    # 分割回測資料
    split_date = pd.Timestamp(SPLIT_DATE)
    twii_backtest_df = twii_full_df[twii_full_df.index >= split_date]
    print(f"  回測期間: {twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}")
    print(f"  資料筆數: {len(twii_backtest_df)}")
    
    # =========================================================================
    # 執行回測
    # =========================================================================
    print("\n[Backtest] 開始無濾網回測...")
    backtester = NoFilterBacktester(buy_model, sell_model, INITIAL_CAPITAL)
    metrics = backtester.run(twii_backtest_df, hybrid.FEATURE_COLS)
    
    # =========================================================================
    # 印出績效
    # =========================================================================
    print("\n" + "=" * 60)
    print("📊 績效摘要 (無濾網 V4)")
    print("=" * 60)
    print(f"  初始資金:   ${metrics['initial_capital']:,.0f}")
    print(f"  最終淨值:   ${metrics['final_value']:,.0f}")
    print(f"  總報酬率:   {metrics['total_return']*100:+.2f}%")
    print(f"  年化報酬:   {metrics['annualized_return']*100:+.2f}%")
    print(f"  夏普值:     {metrics['sharpe_ratio']:.2f}")
    print(f"  最大回撤:   {metrics['max_drawdown']*100:.2f}%")
    print("-" * 60)
    print(f"  交易次數:   {metrics['total_trades']}")
    print(f"  勝率:       {metrics['win_rate']*100:.1f}%")
    print(f"  平均報酬:   {metrics['avg_return']*100:+.2f}%")
    print(f"  平均持有:   {metrics['avg_hold_days']:.1f} 天")
    print("=" * 60)
    
    # =========================================================================
    # 視覺化
    # =========================================================================
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    
    # 子圖 1: Portfolio Value vs Benchmark
    ax1 = axes[0]
    equity_df = metrics['equity_df']
    
    ax1.plot(equity_df.index, equity_df['value'], label='V4 (No Filter)', color='blue', linewidth=2)
    
    # Benchmark
    bench_slice = twii_full_df.loc[equity_df.index[0]:equity_df.index[-1]]['Close']
    bench_normalized = bench_slice / bench_slice.iloc[0] * INITIAL_CAPITAL
    ax1.plot(bench_normalized.index, bench_normalized.values, 
             label='^TWII Buy & Hold', color='gray', linewidth=1.5, alpha=0.7)
    
    ax1.set_title('V4 無濾網回測 vs 大盤 (2023-Present)', fontsize=14)
    ax1.set_ylabel('Portfolio Value ($)')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    # 子圖 2: Price with Signals
    ax2 = axes[1]
    price_slice = twii_backtest_df['Close']
    ax2.plot(price_slice.index, price_slice.values, label='^TWII Close', color='black', linewidth=1)
    
    if backtester.buy_signals:
        buy_dates, buy_prices = zip(*backtester.buy_signals)
        ax2.scatter(buy_dates, buy_prices, marker='^', color='red', s=100, label='Buy', zorder=5)
    
    if backtester.sell_signals:
        sell_dates, sell_prices = zip(*backtester.sell_signals)
        ax2.scatter(sell_dates, sell_prices, marker='v', color='green', s=100, label='Sell', zorder=5)
    
    ax2.set_title('交易訊號 (無濾網)', fontsize=14)
    ax2.set_ylabel('Price')
    ax2.set_xlabel('Date')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # 儲存圖表
    save_path = os.path.join(RESULTS_PATH, 'backtest_v4_no_filter.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\n[Output] 圖表已儲存: {save_path}")
    plt.close()
    
    # =========================================================================
    # 儲存交易明細
    # =========================================================================
    if backtester.trades:
        trades_df = pd.DataFrame(backtester.trades)
        trades_path = os.path.join(RESULTS_PATH, 'trades_v4_no_filter.csv')
        trades_df.to_csv(trades_path, index=False)
        print(f"[Output] 交易明細: {trades_path}")
        
        print("\n[Trades] 最近 5 筆交易:")
        print(trades_df.tail().to_string(index=False))
    
    print("\n" + "=" * 60)
    print("✅ 回測完成！")
    print("=" * 60)


if __name__ == "__main__":
    main()
