# -*- coding: utf-8 -*-
"""
================================================================================
Daily Operations V4 - 單一策略每日維運腳本 (輕量化微調版本)
================================================================================
專為 V4 模型設計的每日維運腳本 (輕量化 Fine-tune)

功能：
1. LSTM 每日重訓與封存 (動態天數 + split_ratio 0.99)
2. 隔離式特徵工程 (模型注入)
3. V4 單一策略推論
4. 簡化報告輸出

V4 特點：
- Buy Fine-tune: 200K 步 (保留更多預訓練知識)
- Sell Fine-tune: 100K 步

作者：Phil Liang (Generated by Gemini)
日期：2025-12-07
================================================================================
"""

import os
import sys
import shutil
import pickle
import subprocess
import json
import glob
from datetime import datetime, timedelta

# 設定 UTF-8 輸出
sys.stdout.reconfigure(encoding='utf-8')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
from tensorflow import keras
from keras import layers

# =============================================================================
# 引用主系統
# =============================================================================
import ptrl_hybrid_system as core_system

# =============================================================================
# 設定路徑
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
DAILY_RUNS_PATH = os.path.join(PROJECT_PATH, 'daily_runs_v4')  # V4 專用輸出目錄

# V4 模型路徑 (單一策略)
V4_MODEL_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v4')

# LSTM 訓練腳本名稱
SCRIPT_5D = "twii_model_registry_5d.py"
SCRIPT_1D = "twii_model_registry_multivariate.py"

# LSTM 模型預設輸出路徑
DEFAULT_LSTM_5D_DIR = os.path.join(PROJECT_PATH, 'saved_models_5d')
DEFAULT_LSTM_1D_DIR = os.path.join(PROJECT_PATH, 'saved_models_multivariate')


# =============================================================================
# Step 0: 建立當日專屬工作區
# =============================================================================
def create_daily_workspace(date_str: str) -> dict:
    daily_path = os.path.join(DAILY_RUNS_PATH, date_str)
    paths = {
        'root': daily_path,
        'lstm_models': os.path.join(daily_path, 'lstm_models'),
        'lstm_5d': os.path.join(daily_path, 'lstm_models', 'saved_models_5d'),
        'lstm_1d': os.path.join(daily_path, 'lstm_models', 'saved_models_multivariate'),
        'cache': os.path.join(daily_path, 'cache'),
        'reports': os.path.join(daily_path, 'reports'),
    }
    for key, path in paths.items():
        os.makedirs(path, exist_ok=True)
    print(f"[Workspace] 建立當日工作區: {daily_path}")
    return paths


# =============================================================================
# Step 1: LSTM 全量重訓與封存 (動態天數 + 全量學習)
# =============================================================================
def train_and_archive_lstm(workspace: dict, end_date: str):
    print("\n" + "=" * 60)
    print("📚 Step 1: LSTM 全量重訓與封存")
    print("=" * 60)
    
    # 動態計算起始日期
    end_dt = datetime.strptime(end_date, '%Y-%m-%d')
    start_5d = (end_dt - timedelta(days=1800)).strftime('%Y-%m-%d')
    start_1d = (end_dt - timedelta(days=1600)).strftime('%Y-%m-%d')
    
    split_ratio = "0.99"
    
    # 1. 執行 T+5 訓練
    print(f"\n[Training] T+5 Model ({start_5d} ~ {end_date}, split={split_ratio})...")
    script_5d_path = os.path.join(PROJECT_PATH, SCRIPT_5D)
    cmd_5d = [sys.executable, script_5d_path, "train", "--start", start_5d, "--end", end_date, "--split_ratio", split_ratio]
    try:
        subprocess.run(cmd_5d, check=True, timeout=1200, cwd=PROJECT_PATH)
        print("[Training] ✅ T+5 訓練完成")
    except subprocess.CalledProcessError as e:
        print(f"[Error] T+5 訓練失敗: {e}")
        return False
    except FileNotFoundError:
        print(f"[Error] 找不到訓練腳本: {script_5d_path}")
        return False
    except Exception as e:
        print(f"[Error] 執行錯誤: {e}")
        return False

    # 2. 執行 T+1 訓練
    print(f"\n[Training] T+1 Model ({start_1d} ~ {end_date}, split={split_ratio})...")
    script_1d_path = os.path.join(PROJECT_PATH, SCRIPT_1D)
    cmd_1d = [sys.executable, script_1d_path, "train", "--start", start_1d, "--end", end_date, "--split_ratio", split_ratio]
    try:
        subprocess.run(cmd_1d, check=True, timeout=1200, cwd=PROJECT_PATH)
        print("[Training] ✅ T+1 訓練完成")
    except subprocess.CalledProcessError as e:
        print(f"[Error] T+1 訓練失敗: {e}")
        return False
    except FileNotFoundError:
        print(f"[Error] 找不到訓練腳本: {script_1d_path}")
        return False

    # 3. 封存模型
    print("\n[Archive] 封存模型到當日工作區...")
    
    def archive_dir(src_dir, dest_dir):
        if os.path.exists(src_dir):
            if os.path.exists(dest_dir):
                shutil.rmtree(dest_dir)
            shutil.copytree(src_dir, dest_dir)
            print(f"  ✅ 已封存: {os.path.basename(src_dir)} -> {dest_dir}")
        else:
            print(f"  ⚠️ 來源目錄不存在: {src_dir}")

    archive_dir(DEFAULT_LSTM_5D_DIR, workspace['lstm_5d'])
    archive_dir(DEFAULT_LSTM_1D_DIR, workspace['lstm_1d'])
    
    return True


# =============================================================================
# Step 2: 隔離式特徵工程 (模型注入)
# =============================================================================
def isolated_feature_engineering(workspace: dict, end_date: str) -> pd.DataFrame:
    print("\n" + "=" * 60)
    print("🔧 Step 2: 隔離式特徵工程 (模型注入)")
    print("=" * 60)
    
    try:
        from twii_model_registry_5d import SelfAttention
        print("[System] 成功引用原始 SelfAttention 類別")
    except ImportError:
        print("[Error] 無法引用 twii_model_registry_5d，請確認檔案是否存在")
        sys.exit(1)

    def load_model_components(model_dir):
        keras_files = glob.glob(os.path.join(model_dir, "*.keras"))
        if not keras_files: return None, None, None, None
        
        latest_keras = sorted(keras_files)[-1]
        print(f"  ...Loading {os.path.basename(latest_keras)}")
        
        model = keras.models.load_model(latest_keras, custom_objects={'SelfAttention': SelfAttention})

        meta_file = latest_keras.replace('model_', 'meta_').replace('.keras', '.json')
        meta = {}
        if os.path.exists(meta_file):
            try:
                with open(meta_file, 'r', encoding='utf-8') as f:
                    meta = json.load(f)
            except Exception as e:
                print(f"  ⚠️ 載入 meta 失敗: {e}")

        scaler_feat_file = latest_keras.replace('model_', 'feature_scaler_').replace('.keras', '.pkl')
        if not os.path.exists(scaler_feat_file):
             scaler_feat_file = latest_keras.replace('model_', 'scaler_').replace('.keras', '.pkl')
        
        scaler_feat = None
        if os.path.exists(scaler_feat_file):
            with open(scaler_feat_file, 'rb') as f:
                scaler_feat = pickle.load(f)

        scaler_tgt_file = latest_keras.replace('model_', 'target_scaler_').replace('.keras', '.pkl')
        if not os.path.exists(scaler_tgt_file):
             scaler_tgt = scaler_feat
        else:
             with open(scaler_tgt_file, 'rb') as f:
                 scaler_tgt = pickle.load(f)

        return model, scaler_feat, scaler_tgt, meta

    print("\n[Model Injection] 載入當日封存的 LSTM 模型...")
    m5d, sf5d, st5d, meta5d = load_model_components(workspace['lstm_5d'])
    m1d, sf1d, st1d, meta1d = load_model_components(workspace['lstm_1d'])
    
    if m5d is None or m1d is None:
        print("[Error] 模型載入失敗，無法進行特徵工程")
        sys.exit(1)

    print("\n[Model Injection] 注入 core_system._LSTM_MODELS...")
    if not hasattr(core_system, '_LSTM_MODELS'):
        core_system._LSTM_MODELS = {}
    
    core_system._LSTM_MODELS.update({
        'model_5d': m5d, 'scaler_feat_5d': sf5d, 'scaler_tgt_5d': st5d, 'meta_5d': meta5d,
        'model_1d': m1d, 'scaler_feat_1d': sf1d, 'scaler_tgt_1d': st1d, 'meta_1d': meta1d,
        'loaded': True
    })
    print("  ✅ 注入完成 (含 Target Scalers)")

    end_dt = datetime.strptime(end_date, '%Y-%m-%d') + timedelta(days=1)
    download_end = end_dt.strftime('%Y-%m-%d')
    print(f"\n[Compute] 下載數據 (2020-01-01 ~ {end_date}, yf.end={download_end})...")
    raw_df = yf.download("^TWII", start="2020-01-01", end=download_end, auto_adjust=True, progress=False)
    
    if isinstance(raw_df.columns, pd.MultiIndex):
        raw_df.columns = raw_df.columns.get_level_values(0)
    
    actual_last_date = raw_df.index[-1].strftime('%Y-%m-%d')
    print(f"[Data] 實際資料最後日期: {actual_last_date}")
    
    print(f"[Compute] 計算特徵中 (使用當日模型 + 30次 MC Dropout)...")
    df = core_system.calculate_features(raw_df, raw_df, ticker="^TWII", use_cache=False)
    
    cache_file = os.path.join(workspace['cache'], 'twii_features.pkl')
    with open(cache_file, 'wb') as f:
        pickle.dump(df, f)
    print(f"[Cache] 特徵已存檔: {cache_file}")
    
    return df, actual_last_date


# =============================================================================
# Step 3: V4 單一策略推論
# =============================================================================
def single_strategy_inference(workspace: dict, df: pd.DataFrame) -> dict:
    print("\n" + "=" * 60)
    print("🎯 Step 3: V4 策略推論 (輕量化)")
    print("=" * 60)
    
    from stable_baselines3 import PPO
    
    FEATURE_COLS = core_system.FEATURE_COLS
    latest = df.iloc[-1]
    
    features = []
    for col in FEATURE_COLS:
        val = latest.get(col, 0.0)
        features.append(val)
    features = np.array(features, dtype=np.float32).reshape(1, -1)
    
    features = np.nan_to_num(features, nan=0.0, posinf=1.0, neginf=-1.0)
    
    result = {}
    
    buy_path = os.path.join(V4_MODEL_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(V4_MODEL_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        print(f"[Error] V4 模型不存在: {buy_path}")
        return {'error': 'Model not found'}

    try:
        buy_agent = PPO.load(buy_path)
        sell_agent = PPO.load(sell_path)
        
        b_act, _ = buy_agent.predict(features, deterministic=True)
        b_obs = buy_agent.policy.obs_to_tensor(features)[0]
        b_prob = buy_agent.policy.get_distribution(b_obs).distribution.probs.detach().cpu().numpy()[0]
        
        s_feat = np.concatenate([features[0], [1.0]]).reshape(1, -1)
        s_act, _ = sell_agent.predict(s_feat, deterministic=True)
        
        result = {
            'buy_signal': 'BUY' if b_act[0] == 1 else 'WAIT',
            'buy_prob': float(b_prob[1]) if b_act[0] == 1 else float(b_prob[0]),
            'sell_signal': 'SELL' if s_act[0] == 1 else 'HOLD'
        }
        
        buy_icon = "🚀" if result['buy_signal'] == 'BUY' else "💤"
        sell_icon = "📤" if result['sell_signal'] == 'SELL' else "🛡️"
        print(f"  {buy_icon} Buy:  {result['buy_signal']} ({result['buy_prob']:.1%})")
        print(f"  {sell_icon} Sell: {result['sell_signal']}")
        
    except Exception as e:
        result = {'error': str(e)}
        print(f"  [Error] 推論失敗: {e}")
        import traceback
        traceback.print_exc()

    return result


# =============================================================================
# Step 4: 輸出報告
# =============================================================================
def generate_report(workspace: dict, df: pd.DataFrame, res: dict, date_str: str):
    print("\n" + "=" * 60)
    print("📊 Step 4: 戰情儀表板 (V4)")
    print("=" * 60)
    
    last = df.iloc[-1]
    
    lines = []
    lines.append("=" * 50)
    lines.append(f"📅 日期: {date_str}")
    lines.append("=" * 50)
    
    lines.append("\n📈 [市場數據]")
    lines.append(f"   收盤價: {last['Close']:.2f}")
    lines.append(f"   成交量: {last['Volume']/1e8:.2f} 億")
    
    lines.append("\n🔮 [分析師 LSTM]")
    pred_1d = last.get('LSTM_Pred_1d', 0) * 100
    pred_5d = last.get('LSTM_Pred_5d', 0) * 100
    conf_5d = last.get('LSTM_Conf_5d', 0) * 100
    
    lines.append(f"   T+1 預測漲跌: {pred_1d:+.2f}%")
    lines.append(f"   T+5 預測漲跌: {pred_5d:+.2f}%")
    lines.append(f"   信心度:       {conf_5d:.1f}%")
    
    lines.append("\n🤖 [操盤手 V4] (輕量化)")
    if 'error' not in res:
        buy_icon = "🚀" if res['buy_signal'] == 'BUY' else "💤"
        sell_icon = "📤" if res['sell_signal'] == 'SELL' else "🛡️"
        lines.append(f"   {buy_icon} 買進訊號: {res['buy_signal']} ({res['buy_prob']:.1%})")
        lines.append(f"   {sell_icon} 賣出訊號: {res['sell_signal']}")
        
        if res['buy_signal'] == 'BUY':
            if conf_5d >= 80:
                advice = "⭐⭐ 高信心買進 (High Confidence Buy)"
            else:
                advice = "⚠️ 低信心買進 (Low Confidence Buy)"
        elif res['sell_signal'] == 'SELL':
            advice = "📤 建議賣出 (Sell)"
        else:
            advice = "💤 空手觀望 (Wait)"
    else:
        lines.append(f"   ❌ 錯誤: {res['error']}")
        advice = "❓ 推論失敗"
    
    lines.append("\n" + "-" * 50)
    lines.append(f"💡 綜合建議: {advice}")
    lines.append("=" * 50)
    
    report = "\n".join(lines)
    print(report)
    
    txt_path = os.path.join(workspace['reports'], 'summary.txt')
    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write(report)
    
    json_path = os.path.join(workspace['reports'], 'summary.json')
    json_data = {
        'date': date_str,
        'generated_at': datetime.now().isoformat(),
        'version': 'V4',
        'market': {
            'close': float(last.get('Close', 0)),
            'volume': float(last.get('Volume', 0)),
        },
        'lstm': {
            'pred_1d': float(last.get('LSTM_Pred_1d', 0)),
            'pred_5d': float(last.get('LSTM_Pred_5d', 0)),
            'conf_5d': float(last.get('LSTM_Conf_5d', 0)),
        },
        'v4_strategy': res,
        'advice': advice,
    }
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(json_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n[Report] 已儲存: {txt_path}")
    print(f"[Report] 已儲存: {json_path}")


# =============================================================================
# Main
# =============================================================================
def main():
    today = datetime.now()
    if today.weekday() == 5: today -= timedelta(days=1)
    elif today.weekday() == 6: today -= timedelta(days=2)
    
    date_str = today.strftime('%Y-%m-%d')
    print("=" * 60)
    print(f"🚀 V4 每日維運系統 (輕量化) - {date_str}")
    print("=" * 60)
    
    if not os.path.exists(os.path.join(V4_MODEL_PATH, 'ppo_buy_twii_final.zip')):
        print(f"\n[Error] V4 模型不存在: {V4_MODEL_PATH}")
        print("請先執行 train_v4_models.py 完成訓練")
        sys.exit(1)
    
    ws = create_daily_workspace(date_str)
    
    train_and_archive_lstm(ws, date_str)
    
    df, actual_date = isolated_feature_engineering(ws, date_str)
    
    if actual_date != date_str:
        print(f"[Warning] 預估日期 {date_str} 與實際資料日期 {actual_date} 不同")
        print(f"[Info] 報告將使用實際資料日期: {actual_date}")
    
    res = single_strategy_inference(ws, df)
    
    generate_report(ws, df, res, actual_date)
    
    print("\n" + "=" * 60)
    print("✅ V4 每日維運完成！")
    print("=" * 60)


if __name__ == "__main__":
    main()
